### ISSUE TITLE
0.7.2 fails to build on GCC 12.1.1

### ISSUE THREAD

**Issue by vt-alt** [simd-everywhere/simde#958]
Full build log https://git.altlinux.org/beehive/logs/Sisyphus/x86_64/archive/2022/0602/error/simde-0.7.2-alt2 please search by word `error:`. Excerpt
```
[997/1748] Compiling C object test/arm/neon/ext-emul-c.p/ext.c.o
FAILED: test/arm/neon/ext-emul-c.p/ext.c.o 
cc -Itest/arm/neon/ext-emul-c.p -Itest/arm/neon -I../test/arm/neon -I. -I.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -O2 -g -pipe -frecord-gcc-switches -Wall -g -O2 -flto=auto -fopenmp-simd -DSIMDE_ENABLE_OPENMP -Wno-psabi -DSIMDE_TEST_BARE -DSIMDE_NO_NATIVE -MD -MQ test/arm/neon/ext-emul-c.p/ext.c.o -MF test/arm/neon/ext-emul-c.p/ext.c.o.d -o test/arm/neon/ext-emul-c.p/ext.c.o -c ../test/arm/neon/ext.c
In file included from ../test/arm/neon/../../test.h:6,
                 from ../test/arm/neon/test-neon.h:4,
                 from ../test/arm/neon/ext.c:3:
../test/arm/neon/ext.c: In function вЂtest_simde_vext_f32вЂ™:
../test/arm/neon/../../../simde/simde-common.h:251:69: error: invalid element index вЂ(signed char)simde_vext_f32_nвЂ™ to вЂ__builtin_shufflevectorвЂ™
  251 | #      define SIMDE_SHUFFLE_VECTOR_(elem_size, vec_size, a, b, ...) __builtin_shufflevector(a, b, __VA_ARGS__)
      |                                                                     ^~~~~~~~~~~~~~~~~~~~~~~
../test/arm/neon/../../../simde/arm/neon/ext.h:65:36: note: in expansion of macro вЂSIMDE_SHUFFLE_VECTOR_вЂ™
   65 |         simde_vext_f32_r_.values = SIMDE_SHUFFLE_VECTOR_(32, 8, simde_float32x2_to_private(a).values, simde_float32x2_to_private(b).values, \
      |                                    ^~~~~~~~~~~~~~~~~~~~~
../test/arm/neon/../../../simde/simde-constify.h:62:24: note: in expansion of macro вЂsimde_vext_f32вЂ™
   62 |       case 0: result = func_name(__VA_ARGS__, 0); break; \
      |                        ^~~~~~~~~
../test/arm/neon/ext.c:58:5: note: in expansion of macro вЂSIMDE_CONSTIFY_2_вЂ™
   58 |     SIMDE_CONSTIFY_2_(simde_vext_f32, r, (HEDLEY_UNREACHABLE(), a), n, a, b);
      |     ^~~~~~~~~~~~~~~~~
```
(ps. Incorrect chars is perhaps utf-8 quotes).

**Comment by mr-c** [comment]
Thanks @vt-alt for the report; can you try with the latest development code?

https://github.com/simd-everywhere/simde/commit/dd0b662fd8cf4b1617dbbb4d08aa053e512b08e4 for example

**Comment by vt-alt** [comment]
@mr-c With dd0b662f it builds successfully without errors (still warnings and notes though) and all tests are passed Ok!

**Comment by vt-alt** [comment]
@mr-c Will there be patch to build 0.7.2 or we should wait for 0.7.3 any time soon?

**Comment by mr-c** [comment]
No patch for 0.7.2; we hope to release 0.8 in the next month or two

**Comment by vt-alt** [comment]
@mr-c Thanks! In meantime I had to delete `simde` package for ALT (because it's not rebuildable and we switched to GCC 12).

**Comment by mr-c** [comment]
@vt-alt feel free to make a snapshot SIMDe package for ALT, perhaps named version "0.7.3~0.20220504.dd0b662" or similar (I don't know how your versioning rules work)

**Comment by vt-alt** [comment]
Ah IC thanks! I found that Fedora is already released 0.7.3 for Rawhide.

https://repology.org/project/simde/history
https://src.fedoraproject.org/rpms/simde/blob/rawhide/f/simde.spec

**Comment by dvzrv** [comment]
Hi! This is still an issue and I am unable to rebuild this project for Arch Linux currently.
We're also on gcc 12.2.1.

**Comment by dvzrv** [comment]
In which commit has this been fixed? It would be good to mention that specific commit instead of a random recent one.
For downstreams it is not so great to go hunting in the history of this project to figure out what to cherry-pick (if even possible).

**Comment by mr-c** [comment]
Hello @dvzrv . I used `git bisect` to find the first commit that builds on gcc 12.2: https://github.com/simd-everywhere/simde/commit/f1de709a55f46646c6dd9e7cda1599cc3de5a24b ; However, I would recommend packaging/using the [0.7.4-rc2 pre-release](https://github.com/simd-everywhere/simde/releases/tag/v0.7.4-rc2) instead

**Comment by dvzrv** [comment]
Thanks for looking into that! I'm a bit reluctant to package a pre-release, since we try to go for stable releases only.

What is the timeline for a 0.7.4 stable release? After all simde can currently not really be packaged using a stable release (which affects any other packages requiring it).

Going forward it would be very good if releases were tested against current compiler versions (once they are out) and patches were backported, as having no working (with current compiler versions) stable version for nearly a year is not so good.

**Comment by mr-c** [comment]
> Thanks for looking into that! I'm a bit reluctant to package a pre-release, since we try to go for stable releases only.
> 
> What is the timeline for a 0.7.4 stable release? After all simde can currently not really be packaged using a stable release (which affects any other packages requiring it).

The checklist is at https://github.com/simd-everywhere/simde/issues/983 ; seems that some tests for newer functions fail in unpopular archs 

> 
> Going forward it would be very good if releases were tested against current compiler versions (once they are out) and patches were backported, as having no working (with current compiler versions) stable version for nearly a year is not so good.

I would also be happy for that. Alas the primary author and maintainer is missing for a while now, so such improvements will depend on the contributions from volunteers. I'm the backup maintainer and already overworked in other areas. 

For example, I did a casual test with GCC 13; which worked, but it hasn't been added to the CI yet. Maybe you could help us with that?

**Comment by dvzrv** [comment]
> The checklist is at #983 ; seems that some tests for newer functions fail in unpopular archs

Thanks!

> > Going forward it would be very good if releases were tested against current compiler versions (once they are out) and patches were backported, as having no working (with current compiler versions) stable version for nearly a year is not so good.
> 
> I would also be happy for that. Alas the primary author and maintainer is missing for a while now, so such improvements will depend on the contributions from volunteers. I'm the backup maintainer and already overworked in other areas.

Oh... that's bad :cry: 
 
> For example, I did a casual test with GCC 13; which worked, but [gcc 13 hasn't been added to the CI yet. Maybe you could help us with that?](https://github.com/simd-everywhere/simde/issues/994)

Unfortunately, with me you're asking someone that maintains a couple hundred of packages for a Linux distribution, with additional numerous projects in various languages. So I respectfully have to decline here ;-)
