### ISSUE TITLE
Ubuntu Bionic ppc64el cross-compiler does not know about `vec_neg`

### ISSUE THREAD

**Issue by milot-mirdita** [simd-everywhere/simde#535]
To reproduce run:

```
# bionic docker (gcc 7.4)
docker run -it --rm ubuntu:bionic

# run inside the docker the following commands for cross-compilation
ARCH=ppc64el
CPREF=powerpc64le
SIMD=POWER9
dpkg --add-architecture $ARCH
cat << HEREDOC | sudo tee /etc/apt/sources.list
deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ bionic main restricted universe multiverse
deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ bionic-updates main restricted universe multiverse
deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
deb [arch=amd64,i386] http://security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
deb [arch=$ARCH] http://ports.ubuntu.com/ubuntu-ports/ bionic main  universe multiverse
deb [arch=$ARCH] http://ports.ubuntu.com/ubuntu-ports/ bionic-updates main universe multiverse
deb [arch=$ARCH] http://ports.ubuntu.com/ubuntu-ports/ bionic-backports main universe multiverse
deb [arch=$ARCH] http://ports.ubuntu.com/ubuntu-ports/ bionic-security main universe multiverse
HEREDOC
apt update -yq
apt install -yq crossbuild-essential-$ARCH cmake vim zlib1g-dev:$ARCH libbz2-dev:$ARCH git
git clone https://github.com/soedinglab/mmseqs2.git
cd mmseqs2
mkdir build
cd build
CC=${CPREF}-linux-gnu-gcc CXX=${CPREF}-linux-gnu-g++ cmake .. -DHAVE_${SIMD}=1 -DBUILD_SHARED_LIBS=OFF -DCMAKE_EXE_LINKER_FLAGS="-static -static-libgcc -static-libstdc++" -DCMAKE_FIND_LIBRARY_SUFFIXES=".a"
make -j
```

Compilation fails with something like
```
[  3%] Building CXX object lib/ksw2/CMakeFiles/ksw2.dir/ksw2_extz2_sse.cpp.o
In file included from /home/vsts/work/1/s/lib/simde/simde/x86/sse4.1.h:27:0,
                 from /home/vsts/work/1/s/lib/ksw2/ksw2_extz2_sse.cpp:35:
/home/vsts/work/1/s/lib/simde/simde/x86/sse.h: In function ‘simde__m128 simde_x_mm_negate_ps(simde__m128)’:
/home/vsts/work/1/s/lib/simde/simde/x86/sse.h:2927:24: error: ‘vec_neg’ was not declared in this scope
       r_.altivec_f32 = vec_neg(a_.altivec_f32);
                        ^~~~~~~
/home/vsts/work/1/s/lib/simde/simde/x86/sse.h:2927:24: note: suggested alternative: ‘vec_nor’
       r_.altivec_f32 = vec_neg(a_.altivec_f32);
                        ^~~~~~~
                        vec_nor
In file included from /home/vsts/work/1/s/lib/simde/simde/x86/sse3.h:30:0,
                 from /home/vsts/work/1/s/lib/simde/simde/x86/ssse3.h:30,
                 from /home/vsts/work/1/s/lib/simde/simde/x86/sse4.1.h:31,
                 from /home/vsts/work/1/s/lib/ksw2/ksw2_extz2_sse.cpp:35:
/home/vsts/work/1/s/lib/simde/simde/x86/sse2.h: In function ‘simde__m128d simde_x_mm_negate_pd(simde__m128d)’:
/home/vsts/work/1/s/lib/simde/simde/x86/sse2.h:6593:24: error: ‘vec_neg’ was not declared in this scope
       r_.altivec_f64 = vec_neg(a_.altivec_f64);
                        ^~~~~~~
/home/vsts/work/1/s/lib/simde/simde/x86/sse2.h:6593:24: note: suggested alternative: ‘vec_nor’
       r_.altivec_f64 = vec_neg(a_.altivec_f64);
                        ^~~~~~~
                        vec_nor
lib/ksw2/CMakeFiles/ksw2.dir/build.make:79: recipe for target 'lib/ksw2/CMakeFiles/ksw2.dir/ksw2_extz2_sse.cpp.o' failed
```

Cross-compilation works on Ubuntu 20.04 (gcc 9.3).

According to this [site](http://www.rowleydownload.co.uk/arm/documentation/gnu/gcc/PowerPC-AltiVec-Built_002din-Functions-Available-on-ISA-2_002e07.html) `vec_neg` should also be available on Power8 so the `defined(SIMDE_POWER_ALTIVEC_P9_NATIVE)` check around it's use might also be not quite correct.

**Comment by nemequ** [comment]
The relevant GCC commit is [r247841](https://github.com/gcc-mirror/gcc/commit/5562ebfc6456b545c500b7d22ea8bceb446fb9fc). The first release containing that commit was 8.1.0.
