### ISSUE TITLE
AVX512 not working with MSVC compiler VS 17.12.1

### ISSUE THREAD

**Issue by mtoeltsch** [simd-everywhere/simde#1237]
We use Simde 0.8.4 to port our MSVC project to macOS/ARM. For performance reasons, we use AVX2/AVX512 intrinsics a lot in the core algorithms. 

The problem is:

As soon as we include avx512.h like this:

#define SIMDE_ENABLE_NATIVE_ALIASES
#include "simde/x86/avx512.h"

the Microsoft compiler shows these errors:

1>C:\Users\mtoeltsch\dev\DSS\DeepSkyStackerKernel\simde\x86\avx512\types.h(622,25): error C2371: '__m512': redefinition; different basic types
1>(compiling source file '/avx.cpp')
1> C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include\zmmintrin.h(47,61):
1> see declaration of '__m512'
1>C:\Users\mtoeltsch\dev\DSS\DeepSkyStackerKernel\simde\x86\avx512\types.h(623,26): error C2371: '__m512i': redefinition; different basic types
1>(compiling source file '/avx.cpp')

Note that we do not include zmmintrin.h or any other intrinsics header file. 
BTW: You get similar problems, if you do the same with the Compiler Explorer ( https://simde.netlify.app/godbolt/demo ).

**Comment by mr-c** [comment]
@mtoeltsch Thank you for your report. What is the MSVC version? Can you try a newer or older version?

**Comment by mtoeltsch** [comment]
> @mtoeltsch Thank you for your report. What is the MSVC version? Can you try a newer or older version?

Hi Michael, 
thanks for your quick reply. It's Visual Studio 17.12.1. There is no newer version. 17.12.0 had the same problem AFAI remember. 
Hmmm, I could try to install one of the 17.11 versions, or - maybe quicker - could try different versions on Compiler Explorer.

**Comment by mtoeltsch** [comment]
I tried on Compiler Explorer:
VS 17.10
VS 17.0
VS 16.11
VS 16.0
They all have the same problem. Hundreds of errors and warnings as soon as you include "avx512.h". 
Mainly redefinitions, e.g. of __m256. Etc.

**Comment by mr-c** [comment]
Thank you @mtoeltsch for that additional information. We never tested `SIMDE_ENABLE_NATIVE_ALIASES` with MSVC, so that is why this was not found sooner.

A fix would be welcome. You can work around this by leaving out `SIMDE_ENABLE_NATIVE_ALIASES` and adding the `simde_` prefix. To automate that, see the script [`test/native-aliases.sh`](https://github.com/simd-everywhere/simde/blob/master/test/native-aliases.sh).

**Comment by mtoeltsch** [comment]
> You can work around this by leaving out `SIMDE_ENABLE_NATIVE_ALIASES` and adding the `simde_` prefix. To automate that, see the script [`test/native-aliases.sh`](https://github.com/simd-everywhere/simde/blob/master/test/native-aliases.sh).

Puh, I'm very reluctant to make those changes to all our intrinsics in the code (adding `simde_` ), there are about 2000 of them.
And probably another 1000-2000 variables of different vector types (__m256, __m512, ...).
It's not a question of automating that change, it's more a question of being "locked-in" to Simde. We would then always need Simde (8MB header files!) for compilation. 

Can you please keep me posted as soon as a fix is available? 
Thanks, 
Martin

**Comment by mr-c** [comment]
> Can you please keep me posted as soon as a fix is available?

Of course, you will be informed via this issue.

Looking at https://github.com/simd-everywhere/simde/blob/60a3a24462d5c074f669ed8b39c85f5b1128108f/simde/x86/avx512/types.h#L45 it seems this is a general issue with MSVC, perhaps `clang-cl` will work better for you?

To set expectations, it is unlikely that I will be personally providing a fix. MSVC is outside the area of my expertise.

**Comment by mtoeltsch** [comment]
> it seems this is a general issue with MSVC, perhaps `clang-cl` will work better for you?

I agree. It seems as MSVC always "consults/inspects" <immintrin.h> (not to say "includes"), even if you don't explicitlx #include it. No idea though, how/why this is done ...

> To set expectations, it is unlikely that I will be personally providing a fix. MSVC is outside the area of my expertise.

No problem. At the moment we get away with include either <immintrin.h> or "simde/x86/..." depending on platform/compiler.
Just one question: Wouldn't it be better to put all your functions into an own namespace "simde" rather than work with prefixes? That I think would make life a lot easier, right?

**Comment by mr-c** [comment]
> Just one question: Wouldn't it be better to put all your functions into an own namespace "simde" rather than work with prefixes? That I think would make life a lot easier, right?

I don't think that would work for C users

**Comment by beru** [comment]
MSVC's `complex` header file included with `#include <complex>` from simde header file ([link](https://github.com/simd-everywhere/simde/blob/d62ab5a134e57c1c2f0218a90db2f3af9d04562b/simde/simde-complex.h#L120)) causes this problem.

<details>

![image](https://github.com/user-attachments/assets/d845de67-f0ca-4fcd-9918-ba7d14641fac)

</details>

The workaround I could find is to copy the header file and use the modified file.

<details>

![image](https://github.com/user-attachments/assets/a35bfbae-0be0-40c9-a508-1afff07957bf)

![image](https://github.com/user-attachments/assets/2012d765-b7c9-4934-93b3-5ec7499d300a)

</details>

**Comment by mtoeltsch** [comment]
> MSVC's `complex` header file included with `#include <complex>` from simde header file ([link](https://github.com/simd-everywhere/simde/blob/d62ab5a134e57c1c2f0218a90db2f3af9d04562b/simde/simde-complex.h#L120)) causes this problem.
> 

Thanks for your analysis. 

> 
> But why do you need to use simde library with MSVC compiler? How about writing this way?
> 
> ```c++
> #if _MSC_VER
> #include <intrin.h>
> #else
> #define SIMDE_ENABLE_NATIVE_ALIASES
> #include "simde/x86/avx512.h"
> #endif
> ```
> 

Yes, that's what we do anyway. 
The disadvantage is just, that <immintrin.h> provides/implements different things than simde/x86/...  does (and vice versa). So we always have to use the "least common multiple" of both.
